name: Pointer
version: 0.11
abstract: Object Oriented Memory Pointers in Pure Perl
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spiffy: 0.23
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
